# Generated by Django 4.2.16 on 2025-08-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_remove_book_category_author_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books_app.category'),
        ),
    ]
