# Generated by Django 4.2.16 on 2025-08-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_alter_author_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_app.category'),
            preserve_default=False,
        ),
    ]
